version: '3.9'

services:
  server:
    container_name: atom_chat_server
    build: ./server/
    restart: on-failure
    command: bash -c "alembic upgrade head && uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload"
    ports:
      - 8000:8000
    volumes:
      - ./server/:/project/
    env_file:
      - ./server/.dev.env
    depends_on:
      - db

  client:
    container_name: atom_chat_client
    build: ./client/
    restart: on-failure
    command: bash -c "npm run dev"
    ports:
      - "5000:5000"
    volumes:
      - ./client/atom_chat/:/app
      - node_modules:/app/node_modules
    depends_on:
      - server

  db:
    container_name: atom_chat_db
    image: postgres:latest
    restart: on-failure
    ports:
      - 5432:5432
    env_file:
      - ./server/.dev.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./pg-scripts:/docker-entrypoint-initdb.d

  pgadmin:
    container_name: db_admin
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    env_file:
      - ./server/.dev.env
    depends_on:
      - db

volumes:
  postgres_data:
  node_modules:
