"""Add user.is_blocked and user.is_deleted

Revision ID: 97074fd6ce09
Revises: 259dd43c7120
Create Date: 2024-10-25 21:02:29.580853

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97074fd6ce09'
down_revision: Union[str, None] = '259dd43c7120'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('is_blocked', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_blocked')
    op.drop_column('users', 'is_deleted')
    # ### end Alembic commands ###
