"""Rename columns

Revision ID: 2137e50741e0
Revises: 2ae45f81bda7
Create Date: 2024-11-01 20:26:43.364906

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2137e50741e0'
down_revision: Union[str, None] = '2ae45f81bda7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('altered_user_id', sa.Uuid(), nullable=True))
    op.drop_constraint('events_added_user_id_fkey', 'events', type_='foreignkey')
    op.create_foreign_key(None, 'events', 'users', ['altered_user_id'], ['user_id'], ondelete='CASCADE')
    op.drop_column('events', 'added_user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('added_user_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.create_foreign_key('events_added_user_id_fkey', 'events', 'users', ['added_user_id'], ['user_id'], ondelete='CASCADE')
    op.drop_column('events', 'altered_user_id')
    # ### end Alembic commands ###
