"""Add trigram indexes

Revision ID: 93ed8d800b83
Revises: 81a6352432f5
Create Date: 2024-10-30 17:37:20.642263

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "93ed8d800b83"
down_revision: Union[str, None] = "81a6352432f5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm;")
    op.execute("SET pg_trgm.similarity_threshold = 0.15;")

    op.create_index(
        "users_username_trgm_idx",
        "users",
        ["username"],
        postgresql_using="gin",
        postgresql_ops={"username": "gin_trgm_ops"},
    )

    op.create_index(
        "chats_title_trgm_idx",
        "chats",
        ["title"],
        postgresql_using="gin",
        postgresql_ops={"title": "gin_trgm_ops"},
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("users_username_trgm_idx", table_name="users")
    op.drop_index("chats_title_trgm_idx", table_name="chats")
    # ### end Alembic commands ###
