"""Add 'events' table

Revision ID: a1dde47d6d69
Revises: 93ed8d800b83
Create Date: 2024-10-31 21:42:51.296411

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1dde47d6d69'
down_revision: Union[str, None] = '93ed8d800b83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('chat_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.chat_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.drop_index('chats_title_trgm_idx', table_name='chats', postgresql_using='gin')
    op.drop_index('users_username_trgm_idx', table_name='users', postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('users_username_trgm_idx', 'users', ['username'], unique=False, postgresql_using='gin')
    op.create_index('chats_title_trgm_idx', 'chats', ['title'], unique=False, postgresql_using='gin')
    op.drop_table('events')
    # ### end Alembic commands ###
