"""Add 'events.added_user_id' column

Revision ID: 056d50aee7a3
Revises: a1dde47d6d69
Create Date: 2024-11-01 19:48:49.397944

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '056d50aee7a3'
down_revision: Union[str, None] = 'a1dde47d6d69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('added_user_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'events', 'users', ['added_user_id'], ['user_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.drop_column('events', 'added_user_id')
    # ### end Alembic commands ###
